openapi: 3.0.1
info:
  title: HubMessageManagementV2
  description: "## Introduction\n The HubMessageManagement push API retrieves the current list of B2B and B2M stop files. Business transactions are sent as aseXML documents carried as payloads inside the API message and transmitted over HTTPS. \n\nParticipants can also use this API to:\n1. Ensure technical requirements required to connect to the e-Hub are validated (for example, appropriate network ports are open).\n2. Ensure their systems can connect to the e-Hub using their SSL certificates and API keys.\n3. Determine if AEMO's e-Hub is operational (ping-pong test)."
  version: v2
servers:
  - url: https://api-prd.aemo.local/HubMessageManagement
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]