openapi: 3.0.1
info:
  title: Pre-Balancing Reports v8
  version: v8
servers:
  - url: https://api-prd.aemo.local/WEM/reports
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]