openapi: 3.0.1
info:
  title: EE Simulation Status Update
  description: "## Introduction\nEE Simulation Status Update APIs are used by EE to submit the simulation status update"
  version: v1
servers:
  - url: https://api-prd.aemo.local/ee-simulation-status-update
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]