openapi: 3.0.1
info:
  title: NEMDispatchBidding
  description: Bidding Service Open API specification
  version: v1
servers:
  - url: https://api-prd.aemo.local/NEMWholesale/bidding
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]