openapi: 3.0.1
info:
  title: WEM DER Installation V2
  description: "## Introduction\nWEM DER Installation API enables the Network Operator to create, update, and retrieve the DER Register information details for the DER installations they have submitted to the DER Register database and to view and resolve associated exceptions"
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/v2/der-register
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]