openapi: 3.0.1
info:
  title: WEM DER NMI
  description: "## Introduction\nUsing the WEM DER Registration APIs, consumers can Create, update and retrieve NMI details"
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/wem/v1/der-register
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]