openapi: 3.0.1
info:
  title: RTMS
  description: The WEM-Reform API for Real-Time Market submissions available to all Market Participants.
  contact:
    name: AEMO Real Time Market Submissions Team
    email: wa.operations@aemo.com.au
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/WEM/v1/realTimeMarketSubmission
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]