openapi: 3.0.1
info:
  title: B2BMessagingPull
  description: "The B2BMessagingPull API is a B2B SMP API used to send and receive B2B messages between the participants in a Pull messaging pattern. The messages will be queued in the e-Hub and the receiving participant can poll the e-Hub, ‘pull’ and process the messages that are queued.\n\n\nFor details on how to get access and business rules for this API:\n\n<a href=\"/api-docs\"><img src=\"./files/ViewAPIDocsButton.png\" alt=\"View API Docs\" /></a>"
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/ws/B2BMessagingPull
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-eHub-APIKey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]