openapi: 3.0.1
info:
  title: Submission
  description: "\n## Introduction\nThe submission API allows participants to submit data to the Gas Bulletin Board (BB).\nData submission from BB reporting entities to the BB are divided into two key areas-\n- Data transfer formats which includes the form, validation rules, and timing of submissions.\n- Data submission methods to the BB, and how the success and failure of those submissions is communicated back to the submitter.\n\nFor details on how to get access and business rules for this API:\n\n<a href=\"/api-docs\"><img src=\"./files/ViewAPIDocsButton.png\" alt=\"View API Docs\" /></a>"
  version: v1
servers:
  - url: https://api-prd.aemo.local/ws/gbb/submission
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]