openapi: 3.0.1
info:
  title: Report
  description: "\n## Introduction\nThe report API allows participants to retrieve data from the Gas Bulletin Board (BB). \n\n\nFor details on how to get access and business rules for this API:\n\n<a href=\"/api-docs\"><img src=\"./files/ViewAPIDocsButton.png\" alt=\"View API Docs\" /></a>"
  version: v1
servers:
  - url: https://api-prd.aemo.local/ws/gbb/report
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]