openapi: 3.0.1
info:
  title: oauth-v1
  description: ''
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/oauth/v1
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]