openapi: 3.0.1
info:
  title: BlindUpdate
  description: "## Introduction\n The BlindUpdateTool API supports Upload of blind update Data by participants facing API's to backend MSATS systems , Download processed Blind Update file, List of all the Blind Update files uploaded by the Participants. \n Participants will access the BlindUpdateTool tab from the Browser which invokes the respective process in the API Management. Uploading the Blind Update File happens which will receive a response from backend Native API after basic validation.Asynchronously, the uploaded file will be processed in the backend and listed with a status in the participants screen.Processed blindupdate files can be downloaded from the screen."
  version: v1
servers:
  - url: https://api-prd.aemo.local/NEMRetail/BlindUpdate
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]