openapi: 3.0.1
info:
  title: MT PASA Offers
  description: "## Introduction\nThe MT PASA Offers API allows Scheduled Generators, Market Customers, Market Network Service Providers, and Integrated Resource Providers to submit their MT PASA Offers for Bi-directional Units (BDU), Scheduled Generation Units (SGU), Scheduled Load Units (SLU), and Scheduled Network Services (SNS). MT PASA Offers are input into the MT PASA process."
  version: ''
servers:
  - url: https://api-prd.aemo.local/NEMWholesale/v1/mtpasaoffers
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]