openapi: 3.0.1
info:
  title: DER Registration for NSPs
  description: "## Introduction\nUsing the DER Registration APIs, NSPs can\n\n• Submit DER Connection Agreement data.\n\n• Provide AC Connections, and Device details in the same submission"
  termsOfService: https://dev.aemo.com.au/terms
  version: v1
servers:
  - url: https://api-prd.aemo.local/NEMWholesale/DER/registration
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: x-apikey
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]