openapi: 3.0.1
info:
  title: DER Registration For Account Holders
  description: "## Introduction\nUsing the DER Registration APIs, Account Holders can\n\n• Submit DER Connection Agreement data.\n\n• Provide AC Connections, and Device details in the same submission"
  version: v1
servers:
  - url: https://api-prd.aemo.local/NEMWholesale/DER/consumer/registration
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: client_id
      in: header
    apiKeyQuery:
      type: apiKey
      name: clientId
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]