openapi: 3.0.1
info:
  title: WEMDE DispatchInstruction
  version: '1.0'
servers:
  - url: https://api-gwy-prd.aemo.local/WEM/v1/dispatchInstruction
  - url: https://api-gwy-prd.aemo.local/WEM/v1/dispatchInstruction
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]