openapi: 3.0.1
info:
  title: GasBB Reporting Public Data
  description: 'This API is intended for AEMO''s use only, used by AEMO web pages and is not supported for any other use. It can change at any time. See https://dev.aemo.com.au/ for information on using AEMO APIs.'
  termsOfService: https://dev.aemo.com.au/terms
  version: v1
servers:
  - url: https://api-prd.aemo.local/gasbb-reporting-data
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: X-DC-DEVKEY
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]