openapi: 3.0.1
info:
  title: OIP
  version: '3.0'
  x-origin:
  - format: openapi
    source: AEMO API Management developer portal
    url: https://dev.aemo.com.au/developer/apis/oip-external-v1/operations?api-version=2022-04-01-preview
servers:
- url: https://api-prd.aemo.local/WEM/v1/outageIntentionPlan
paths:
  /networkOperatorPlanSubmission:
    post:
      operationId: networkOperatorPlanSubmissionPOST
      summary: /networkOperatorPlanSubmission - POST
      tags:
      - OIP
      description: /networkOperatorPlanSubmission - POST
      parameters:
      - name: x-initiatingParticipantId
        in: header
        required: true
        schema:
          type: string
        description: The id of the Initiating Participant
      - name: x-market
        in: header
        required: true
        schema:
          type: string
        description: The id of the market
      requestBody:
        content:
          application/json:
            example:
              requestData:
                calendarYear: 0
                networkOperatorOutageRequests:
                - startTime: string
                  endTime: string
                  equipments:
                  - string
                  description: string
                  impactedFacilities:
                  - string
                  highImpact: true
                  email: string
          text/json:
            example:
              requestData:
                calendarYear: 0
                networkOperatorOutageRequests:
                - startTime: string
                  endTime: string
                  equipments:
                  - string
                  description: string
                  impactedFacilities:
                  - string
                  highImpact: true
                  email: string
          application/*+json:
            example:
              requestData:
                calendarYear: 0
                networkOperatorOutageRequests:
                - startTime: string
                  endTime: string
                  equipments:
                  - string
                  description: string
                  impactedFacilities:
                  - string
                  highImpact: true
                  email: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
          content:
            application/json:
              examples:
                missingHeader:
                  summary: Missing mandatory HTTP header parameter
                  value:
                    transactionId: 61361d96-f20d-43a7-bkdf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '400'
                      title: Missing mandatory HTTP header parameter
                      detail: Mandatory HTTP header <headerName> is missing
                      source: ''
        '401':
          description: API Authentication failure
          content:
            application/json:
              examples:
                unauthorized:
                  summary: Unauthorized
                  value:
                    transactionId: 9a8e902a-ed40-45f3-b075-7a644b12947f
                    data: {}
                    errors:
                    - code: '401'
                      title: Unauthorized
                      detail: Unauthorized
                      source: ''
                initiatingParticipantIdMismatch:
                  summary: x-initiatingParticipantId does not match with participant id associated with
                    certificate
                  value:
                    transactionId: 9a8e902a-ed40-45f3-u475-7a644b12947f
                    data: {}
                    errors:
                    - code: '401'
                      title: Unauthorized
                      detail: x-initiatingParticipantId does not match with participant id associated
                        with certificate
                      source: ''
        '404':
          description: Not Found
          content:
            application/json:
              examples:
                resourceNotFound:
                  summary: Resource Not Found
                  value:
                    transactionId: 61361d96-f09d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '404'
                      title: Not Found
                      detail: Resources for the endpoint URI not found. Endpoint URI:<URI>
                      source: ''
        '405':
          description: Method not allowed
          content:
            application/json:
              examples:
                methodNotAllowed:
                  summary: Method Not Allowed
                  value:
                    transactionId: 61361d96-z20d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '405'
                      title: Method Not Allowed
                      detail: 'Input request HTTP method is <invokedMethod> but operation <operationURI>
                        accepts only: [<operationMethod>]'
                      source: ''
        '413':
          description: Payload Too Large
          content:
            application/json:
              examples:
                payloadTooLarge:
                  summary: Payload Too Large
                  value:
                    transactionId: dc6826bc-1c0d-498b-b474-2b231910860c
                    data: {}
                    errors:
                    - code: '413'
                      title: Payload Too Large
                      detail: Maximum allowed size for the <request/response> body is <payload size limit>
                        bytes (<size limit> MB). This <request/response> has size of <number of bytes>
                        bytes
                      source: ''
        '429':
          description: Too many request
          content:
            application/json:
              examples:
                tooManyRequests:
                  summary: Too Many Requests
                  value:
                    transactionId: 63361d96-f20d-43a7-babf-59b35fab9b13
                    data: {}
                    errors:
                    - code: '429'
                      title: Too Many Requests
                      detail: Number of inbound requests exceeded the throttling limits; try after sometime
                      source: ''
        '500':
          description: Internal Server Error
          content:
            application/json:
              examples:
                applicationUnavailable:
                  summary: Application Unavailable
                  value: ''
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
- {}
- apiKeyHeader: []
- apiKeyQuery: []
tags:
- name: OIP
  description: OIP
