openapi: 3.0.1
info:
  title: Prudentials
  description: This API supports the various operations performed on Prudentials dashboard
  version: v1
servers:
  - url: https://api-prd.aemo.local/NEMWholesale/Prudentials
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]