openapi: 3.0.1
info:
  title: CDR
  description: "## Introduction\nThe Consumer Data Right (CDR) APIs allow Registered Financially Responsible Market Participants (FRMPs) to service API requests for AEMO data from Accredited Data Recipients."
  version: '1.0'
servers:
  - url: https://api-prd.aemo.local/NEMRetail/cds-au/v1/secondary/energy
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - { }
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]